name: autoupdate

on:
  schedule:
    - cron:  '0 0 * * 6'

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Add upstream repo
      run: git remote add upstream https://github.com/TryGhost/Casper.git
    - name: Checkout master
      run: git checkout master
    - name: Merge upstream
      run: git pull upstream main
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        tags: true
